name: Deploy to Vercel
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the source code
      - uses: actions/checkout@v2

      # Build the app
      - name: build
        run: |
          yarn
          yarn build

      # Send it to vercel
      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-comment: false                     # Do not leave a comment on PRs
          vercel-args: "deploy dist --name ${{ secrets.VERCEL_APP_NAME }} --yes -A ./vercel.json --prod"